import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<div className = {styles.nav}>
  <ul>
    <li>About</li>
    <li>Home</li>
    <li>Contact</li>
    <li>Blog</li>
  </ul>
</div>


      <div className = {styles.main}> 
        <h1 className = {styles.title}>Hunting coder</h1>
      <p>A blog for hunting coders by a hunting coder</p>
      <p>How to learn javascript in 2022</p>
      <p>How to learn javascript in 2022</p>
      <p>How to learn javascript in 2022</p>
      <div>

      </div>
      </div>


      </>
      
   
    
    
    
    )}